#!/usr/bin/env python3

import hashlib
import os
import platform
import random
import src.watchdogs as watchdogs # this is something that I'll deal with later
import src.parsers as sparse
import src.constants as bconsts

b_args = sparse.bakeargs()

# Generate list of programs, verify they're all valid.
if b_args.programs == 'all':
	progs = bconsts.BAKEPROGS
else:
	progs = b_args.programs
	watchdogs.verifyprograms(progs)

# Find time commands here

# Setup
print(os.path.abspath(b_args.dna))